namespace VPinCommander.Core.Scanning;

/// <summary>
/// Reads the set of ROM names covered by DirectOutput Framework config files
/// (directoutputconfig*.ini as generated by the DOF Config Tool: one row per
/// game, ROM name before the first comma).
/// </summary>
public static class DofConfigReader
{
    public static HashSet<string> ReadRomNames(string? configFolder)
    {
        var roms = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if (string.IsNullOrWhiteSpace(configFolder) || !Directory.Exists(configFolder))
            return roms;

        foreach (var file in Directory.EnumerateFiles(configFolder, "directoutputconfig*.ini", SearchOption.TopDirectoryOnly))
        {
            string[] lines;
            try
            {
                lines = File.ReadAllLines(file);
            }
            catch (Exception)
            {
                continue; // unreadable config file — treat as absent
            }

            foreach (var rawLine in lines)
            {
                var line = rawLine.Trim();
                if (line.Length == 0 || line[0] is '#' or ';' or '[' or '@')
                    continue;

                var comma = line.IndexOf(',');
                var name = (comma < 0 ? line : line[..comma]).Trim();
                if (IsPlausibleRomName(name))
                    roms.Add(name);
            }
        }
        return roms;
    }

    private static bool IsPlausibleRomName(string name) =>
        name.Length is > 0 and <= 40
        && name.All(c => char.IsLetterOrDigit(c) || c is '_' or '-' or '.');
}
